### ISSUE TITLE
[BUG] : Upload a file bug when selecting the file

### ISSUE THREAD

**Issue by onihilist** [gochan-org/gochan#112]
First of all, I use Edge...

When I try to post an image, for creating a thread or replying to someone, my file explorer is opening twice.
If I just select one time the file, the file is not uploaded, so I have to select the file twice in the two file explorer.

**Comment by Eggbertx** [comment]
This was a known issue and was fixed by of [this](https://github.com/gochan-org/gochan/commit/9170c18df61119e82d01a8ae0ca07ae605fab847) commit. I'm working on a release for it

**Comment by onihilist** [comment]
Oh ok thanks
