### ISSUE TITLE
Add cache layer on top of prepareSQL / implement caching

### ISSUE THREAD

**Issue by comraderat** [gochan-org/gochan#24]
Issue consists of two parts:
1. No sql is cached at all because all statements are closed in the exec-like functions. (which removes the cache). Constantly reused sql statements should never be closed.
2. We can possibly save some performance. If db.prepare doesnt internally cache based on string input, we need to implement manual caching of prepared statements based on hashed string input.

--- old ---

Adding a cache layer on top of/directly at the top of prepareSQL would avoid re-formatting already existing queries.

Current situation:
1. Query is formatted/replaced according to database
2. Query is passed to stmt which has it cached and returns cached version
3. Query is excecuted and then closed, removing the cache.

New situation:
In prepareSQL: Query is hashed and cached stmt statament is returned (if not closed)

**Comment by comraderat** [comment]
Is query even cached if it is closed at the end of functions like ExecSQL?

**Comment by Eggbertx** [comment]
Based on the amount of work it would require to reliably implement this, it probably isn't worth the trouble. Implementing this has the chance of heavily increasing the memory usage and may end up causing several prepared queries to sit in memory, whether or not they're actually repeatedly used or not.

If SQL statement preparation does end up becoming a speed issue and implementing this wouldn't require microoptimization, I'll reopen the issue.
