### ISSUE TITLE
Unit test sql

### ISSUE THREAD

**Issue by comraderat** [gochan-org/gochan#26]
Write a system to unit test existing SQL against real running databases, starting with queries that are non-deprecated with the current version of the database design.
Use vagrant (or whatever we use to virtual box) to automatically set it each database version and run it?

Needed:
- A project that imports the sql package, can connect to a database based on a testing config, allows you to define unit tests on specific functions with buildup (create database, execute population script, add mock data), excecution (run command), assertion and breakdown (drop database)

Would like:
- Possibly using vagrant/docker or whatever we use to set up a virtual box with said project for each database so tests can easily be run by any programmer anywhere.
- Jenkins/automatic testing on a server to do it for you.

**Comment by Eggbertx** [comment]
[This](https://github.com/DATA-DOG/go-sqlmock) looks pretty promising

**Comment by Eggbertx** [comment]
Despite what github-actions thinks, this has had a lot of activity and is still in progress
