### ISSUE TITLE
Implement post editing

### ISSUE THREAD

**Issue by comraderat** [gochan-org/gochan#35]
Posts should be editable
- [x] Name, email and title should be editable
- [x] Text should be editable
- [x] Files should be editable
<s>- [ ] This functionality should only be available to moderators and up</s>

**Comment by Eggbertx** [comment]
Users can edit their posts (if they put in the correct password) as of f483a2f95886ca115300743f6234034315313932 and staff can edit any post, though right now only the post text and subject text are editable. Files can be deleted but not replaced (yet), but that's done separate from the edit screen

**Comment by Eggbertx** [comment]
Emails are now editable, though tripcodes are stored in the database after they are hashed, so changing the name is impossible without having to have the server waste cycles brute-forcing it. I could have it only allow changing the name if the post does not have a tripcode, but that is obnoxious and arbitrary
