### ISSUE TITLE
More file type support

### ISSUE THREAD

**Issue by comraderat** [gochan-org/gochan#37]
More file type support (pdf, epub, sound only, gifs, webms, mp4s, webp’s, jfifs)

**Comment by Eggbertx** [comment]
The only one of those that I have any issue with is the webp format, since someone using an older browser may not be able to view it.

**Comment by comraderat** [comment]
Should we transcode webps we receive to a more normal format?

**Comment by Eggbertx** [comment]
I considered that, but for very large files, that could potentially cause issues if the server is under high traffic.

**Comment by Eggbertx** [comment]
mp4 support has been added by 8ccd217ff0de3c34fdcbbd1858bcbd3cc41e3c07

**Comment by Eggbertx** [comment]
Issue is still being worked on
