### ISSUE TITLE
Custom top bar board formatting

### ISSUE THREAD

**Issue by comraderat** [gochan-org/gochan#39]
Implement custom top bar formatting, accessible via the global config.
This would allow admins to change the top navbar board layout to whatever they want.

Would probably look something like this:
* All text is normal text
* Board links are inserted by enclosing a URI between <>
* To write < or > you escape it with a backslash like `\< \>` so

**Comment by Eggbertx** [comment]
Issue is still being worked on

**Comment by Eggbertx** [comment]
Instead of the formatting described in the OP, it might be simpler to just use a template override
