### ISSUE TITLE
New board

### ISSUE THREAD

**Issue by ghost** [gochan-org/gochan#51]
How to create new boards? In manage?action=boards the "create new board" area is blank, no buttons visible. Also, when in the admin area the quick reply posting dialog box pops up, not sure if that is intentional or not. VERY nice looking app, I have hope that gochan will develop so people can use it. Your board is the coolest one on the internet, I love it.

**Comment by Eggbertx** [comment]
At first I was confused and thought you were talking about the latest release (which it works in), but I just checked and it does look like it somehow got broken at some point. Working on it now.
As for the QR box, I was doing some work on that, I'll fix that issue as well.

**Comment by aileda** [comment]
As soon as it is fixed and one can ad new boards, I will be done with php forever and will be happy to use gochan :) The looks of gochan is a work of art... i will use it in production as soon as i can ad new boards. Even if one has to  to manually ad boards by editing the code or something then that would be cool.

**Comment by aileda** [comment]
![gochan](https://user-images.githubusercontent.com/89950409/148723669-cc1cd817-1ea1-4580-a947-8a7ac8cdf1ab.png)

**Comment by aileda** [comment]
as shown in pic, there is nothing to click on in the create new board section.
