### ISSUE TITLE
image display

### ISSUE THREAD

**Issue by ghost** [gochan-org/gochan#52]
![board-gochan](https://user-images.githubusercontent.com/89950409/148887827-12f295c8-6f9b-4e93-85d0-ca5ddbc62bea.png)

See on far left how it says /test/src? After posting, one has to click that link to make the image show up. Not trying to harp on you, hopefully this post is helpful. Gochan is cool and is my fav board!!!!!

**Comment by Eggbertx** [comment]
If you open the thumbnail (the thumbnail, not the upload) does it give a 404 error?

**Comment by aileda** [comment]
Any updates on the ability to create new boards? Oah, and I will answer your question about the thumbnail in 2 years. You know, just like how you make gochan, then over 2 years in it still does not work at all. Rest assured, I will get right to answering your question about the thumbnails in 2 years tho!!! :)

**Comment by Eggbertx** [comment]
Sorry for the delay. The only reason why I didn't make a new release was because of the major DB change. As soon as I fix the board issue (it's almost done), I'll make an official release.
