### ISSUE TITLE
Help with Docker install

### ISSUE THREAD

**Issue by 3nly** [gochan-org/gochan#67]
Hello, thanks for making gochan.

I'm fairly nooby when it comes to Docker but I'm trying to spin up a local install and I'm faced with this error after running `docker-compose -f docker-compose-mariadb.yaml up --build`:

![dfdsf](https://user-images.githubusercontent.com/59023753/210158836-45c6eee4-b937-402d-b1f8-526048dd0d9d.PNG)

What am I doing wrong? What's this `js` thing? Is this a bug?

What I have and what I did:
- Server running Debian Bullseye
- Installed Docker, Docker Compose and Portainer
- All running fine, server accessible from the outside, ports 80/443 forwarded
- Do a `git clone` of this repo to my root folder
- Edit `docker-compose-mariadb.yaml`
- cd into /gochan/docker folder and run `docker-compose -f docker-compose-mariadb.yaml up --build`
- Build gets stuck forever at error in image above, docker-gochan-1 goes "exited"

Thanks for any help, and happy new year.

**Comment by Eggbertx** [comment]
Oh crap, I forgot about that. I used to provide an already transpiled gochan.js in /html/js but it became a bit unwieldly, having to make sure that the . From the host system, before you bring up the docker image, run `./build.py js`. Make sure you have Node.js and npm installed. If you don't want JavaScript/don't care about JavaScript on your site, you can suppress that error by just doing mkdir html/js instead.

I'll put something in the installation function to catch that and give a warning or something. Sorry about the confusion.

**Comment by 3nly** [comment]
Thank you I got it working now thanks your fixes and instructions. 👍 

![ghdfgh](https://user-images.githubusercontent.com/59023753/210268115-8e4ce6c4-ea67-47e2-83a5-0dc769eab720.PNG)

**Comment by Eggbertx** [comment]
The upcoming release will fix that. If you want JavaScript (for things like the quick reply box and post dropdown) now, you can download the latest release and copy the js directory into the repo's html directory.
