### ISSUE TITLE
Issue running gochan executable: "Error parsing gochan.json: invalid character ']' looking for beginning of valueinvalid ListenIP value: "" "

### ISSUE THREAD

**Issue by bigbullyist** [gochan-org/gochan#71]
For some reason, when I try to run GoChan through systemd, it fails and gives me this error:
![image](https://user-images.githubusercontent.com/91707409/226771382-4e5ee97f-ab19-41fd-a527-89e7c7c74d80.png)

Upon further investigation, I'm given this error when running the executable alone.
![image2](https://user-images.githubusercontent.com/91707409/226771453-23d37c46-2adf-47a6-98a8-b0e81f425bad.png)

I checked my gochan.json file, and I do not see a closing bracket anywhere in the ListenIP line.
As a result, I have no clue what the issue could be, or why I'm given a "gochan.json can't be found" error when it is being read from the second screenshot.

**Comment by onekopaka** [comment]
For the systemd unit, gochan is being started in /, and thus is looking for gochan.json at /gochan.json, /usr/local/etc/gochan/gochcan.json or /etc/gochan/gochan.json. See the source: https://github.com/gochan-org/gochan/blob/master/pkg/config/util.go#L246

You can either add to the systemd unit, under the `[Service]` section  the line `WorkingDirectory=/home/gochan/gochan` or copy the config to one of the two other paths.

As for the ListenIP, what do you have in your file?

**Comment by bigbullyist** [comment]
I have my server's IP as the ListenIP. Wasn't sure if I should leave it localhost or make it that.

**Comment by Eggbertx** [comment]
In most cases, ListenIP can (and possibly should) be left as 127.0.0.1. Set it to that and let us know if that works.

**Comment by bigbullyist** [comment]
It gives me the exact same "invalid character" error when I have it as 127.0.0.1.

**Comment by onekopaka** [comment]
It sounds like there's something else going on in the config file.

Any chance you can share the whole config file? If you upload it here, make sure to remove database passwords, any API keys and the Random Seed.
