### ISSUE TITLE
Another execution error (hope this isn't a bother).

### ISSUE THREAD

**Issue by bigbullyist** [gochan-org/gochan#72]
I'm now getting this when I try to execute:

`Mar 23 22:10:17 grusha systemd[1]: Started gochan Daemon.
Mar 23 22:10:17 grusha gochan[112613]: Starting gochan v3.5.0
Mar 23 22:10:17 grusha gochan[112613]: Connected to database
Mar 23 22:10:17 grusha gochan[112613]: Failed to initialize the database: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'IF EXISTS wordfilters_board_id_fk' at line 1
Mar 23 22:10:17 grusha systemd[1]: gochan.service: Main process exited, code=exited, status=1/FAILURE
Mar 23 22:10:17 grusha systemd[1]: gochan.service: Failed with result 'exit-code'.`

What file is it getting this from so I could check line 1?

**Comment by onekopaka** [comment]
https://github.com/gochan-org/gochan/blob/master/pkg/gcsql/connect.go#L58 seems to be the line in question. What version of MySQL / MariaDB / other are you using?

**Comment by bigbullyist** [comment]
version 8.0.32

**Comment by bigbullyist** [comment]
Will the fix be committed to the repo, and what should I do on my part?

**Comment by Eggbertx** [comment]
Yeah, in the next couple commits and it'll be the focus of the upcoming hotfix release, 3.5.1

**Comment by Eggbertx** [comment]
Sorry about that, the pull request was just supposed to reference this, GitHub seems to have changed it so that it also automatically closes the issue as well.

**Comment by Eggbertx** [comment]
Alright, if you use the latest release, gochan v3.5.1, it should work correctly. If you get an error saying that there are tables missing, or something to that effect, just drop and recreate the gochan database. My goal is for gochan-migration to make having to do that unnecessary.
