### ISSUE TITLE
Federation support

### ISSUE THREAD

**Issue by aicynide** [gochan-org/gochan#86]

**Comment by Eggbertx** [comment]
What do you mean federation? Something like 8chan/kun's ability to make and moderate your own board?

**Comment by aicynide** [comment]
@Eggbertx I mean, use activitypub so that we can comment from other imageboard server or mastodon/pixelfed

**Comment by Eggbertx** [comment]
Oh, right. I'm not very familiar with the workings of federated software (as you can see), but because Gochan is a monolithic system, this might be best handled with an RPC service. Gochan doesn't currently use RPC, but I can set that up and then work on an ActivityPub client to connect to Gochan.

**Comment by Eggbertx** [comment]
I'm still working on RPC support for ActivityPub-based communities, but you can technically link to other imageboards from gochan by [overriding](https://github.com/gochan-org/gochan/blob/master/templates/override/README.md) the [topbar.html](https://github.com/gochan-org/gochan/blob/master/templates/topbar.html) template and adding board links to boards on other imageboards, and vice versa, though the process for altering the board links may vary depending on what imageboard software they use.

**Comment by Eggbertx** [comment]
I've been thinking about this and came to the same conclusion. Since imageboards don't have accounts aside from staff accounts, the closest thing would probably be linking to each other's boards in the top and bottom board lists

**Comment by Eggbertx** [comment]
I'm going to close this issue for the time being, as it would likely take more work than it's worth. If more people are interested, it can be reopened and considered later.
