### ISSUE TITLE
Finish GeoIP support

### ISSUE THREAD

**Issue by Eggbertx** [gochan-org/gochan#93]
The next release (3.10.0) should have GeoIP support finished, with country flags visible on posts, configurable on a per-board basis, or globally enabled

- [x] Country flags on posts
- [x] GeoIP flag usage
- [x] Country detection via geoip (MaxMind GeoIP2/GeoLite2 DB)
- [ ] Legacy GeoIP database support
- [x] Cloudflare IP via [CF-IPCountry](https://developers.cloudflare.com/network/ip-geolocation/) header
- [x] Extendable via Lua

Currently, this is what will likely be used in gochan.json for GeoIP/flag configuration, though this may changed. Comments are included for explanation
```JSONC
{
	// SystemCriticalConfig.GeoIP should be a pointer in the BoardConfig struct, if it is non-nil,
	// GeoIP is assumed to be used
	"GeoIP": {
		// GeoIPType valid values:
		// "" or "none": not used, DBLocation and FlagOptions are ignored
		// "legacy": legacy/MaxMind GeoIP v1 (usually a .dat extension), may or may not end up being supported
		// "geoip2", "mmdb": MaxMind GeoIP2 database support
		// "cloudflare": Use Cloudflare's CF-IPCountry header, only usable if you are using Cloudflare and it is enabled
		"GeoIPType": "legacy",
		"DBLocation": "/path/to/db.{dat,mmdb}"
	},
	// BoardConfig.FlagOptions determines whether GeoIP is enabled for the board (or globally)
	// and what custom country flags are 
	"FlagOptions" {
		"EnableGeoIPFlag": true,
		"EnableNoFlag": true, // if enabled, a "No flag" option will be available in the dropdown and if selected, the post won't show a flag
		"CustomCountries": [
			{"Name": "Benis", "Flag": "spurdo.png"},
			{"Name": "HONK!", "Flag": "clown.png"}
		]
	}
}
```
For the most up to date version of GeoIP and custom flag configuration as development continues, see [gochan.example.json](https://github.com/gochan-org/gochan/blob/geoip/examples/configs/gochan.example.json) in the `geoip` branch.

**Comment by ip2location** [comment]
@Eggbertx This is indeed a nice feature. I would like to introduce the free IP2Location LITE IP geolocation database at https://lite.ip2location.com. If you find it a good fit for gochan, feel free to give me a ping.

**Comment by Eggbertx** [comment]
Thanks for the suggestion, I see you have a Go package for it, so I'll take a look at that.

**Comment by Eggbertx** [comment]
This issue is more or less complete as of [0f36a30](https://github.com/gochan-org/gochan/commit/0f36a300c4e50a0e931fc322ac4076311775391f), with the addition of the ip2location plugin from @ip2location's suggestion. Right now the plugin only supports the database file, not the web services since its API doesn't appear to be well documented (or I just wasn't looking in the right place).
